name = "MakeMore"
uuid = "d75ead45-2eb8-424e-80e3-a1a992c7a711"
authors = ["Tarun Vangani <reachtarunhere@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
